#!/bin/bash
cd /home/ec2-user/linxiaoke/linxiaoke-mv
echo $(date) >> ./updateLog
./getAllSongs.py --user-url http://changba.com/s/h4X81hN_geb7fpHjSxOO1Q >> ./updateLog
./getMeipaiVideos.py --user-url http://meipai.com/user/18239365 >> ./updateLog
git add . >> ./updateLog 2>&1
git commit -m "Update songs" >> ./updateLog 2>&1
git push >> ./updateLog 2>&1
